[package]
name = "rust-wordsearch"
version = "0.1.0"
authors = ["Julien Rouviere <julien.rouviere@gmail.com>"]
edition = "2018"

[lib]
name = "wordsearch"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.20"
features = ["extension-module"]

[dependencies]
rayon = "1.10.0"